### ISSUE TITLE
Roadmap 1.0 

### ISSUE THREAD

**Issue by zaaack** [zaaack/inker#1]
## Features:

* [ ] Profile
   * [ ] unit, rate (wip)
   * [ ] variable (length, color)
* [ ] assets (copy images url)

* [ ] Context Menu
  * [ ] Copy text/css
  * [ ] Hide layer
  * [ ] Copy svg icon (Select outer, select deeper)
  * [ ] Copy png icon

* [ ] Management
* [ ] Web server

* [ ] Android/iOS

 
## Optimizations
* [ ] Rect radius from svg path
* [ ] More test
* [ ] Memory footprint
